export const roadmap = [
  "Python Basics",
  "OOP",
  "Collections",
  "Generators",
  "Decorators",
  "AsyncIO",
  "FastAPI"
];

export const topics = [
  {
    title: "Python Basics & OOP",
    description: "Understand syntax, dynamic typing, scoping, namespaces, and object-oriented capabilities in Python.",
    details: [
      "Dynamic typing, variable bindings, and Python garbage collection (reference counting)",
      "Functions: arg/kwarg packing/unpacking, closures, global/nonlocal scopes",
      "Object-Oriented Python: classes, dunder (magic) methods, multiple inheritance (MRO)",
      "Encapsulation properties, descriptors, and classmethods/staticmethods"
    ]
  },
  {
    title: "Advanced Data Structures & Collections",
    description: "Master built-in collections, slicing, comprehension patterns, and custom mappings.",
    details: [
      "List, Set, Dict comprehension patterns and memory footprints",
      "Slicing mechanics: step strides, copy semantics, and memoryviews",
      "Collections module: Counter, defaultdict, deque, namedtuple",
      "Hashing requirements: Mutable vs Immutable data types"
    ]
  },
  {
    title: "Generators & Iterators",
    description: "Build lazy iterators, evaluate lists on demand, and handle memory-efficient loops.",
    details: [
      "Iterator protocol: __iter__() and __next__() dunder methods implementation",
      "Generator functions using yield and lazy state evaluation",
      "Generator expressions vs list comprehensions memory comparisons",
      "Co-routines transition: using send(), throw(), and close() directives"
    ]
  },
  {
    title: "Decorators & Metaprogramming",
    description: "Wrap functions to extend behaviors dynamically, handle closures, and write class decorators.",
    details: [
      "Function closures, nested scopes, and first-class functions",
      "Writing function decorators, argument propagation (*args, **kwargs), and functools.wraps",
      "Class decorators and writing decorators that accept arguments",
      "Metaprogramming concepts: metaclasses and __new__ vs __init__ executions"
    ]
  },
  {
    title: "AsyncIO & Concurrency",
    description: "Write concurrent single-threaded applications using async/await, loops, and tasks.",
    details: [
      "Asynchronous programming: Event Loop mechanics and cooperative multitasking",
      "Coroutines definition: async def and executing calls via await",
      "Concurrent execution: asyncio.gather, creating tasks, and timeouts handling",
      "CPU-bound vs IO-bound tasks: multiprocessing vs threading vs asyncio"
    ]
  },
  {
    title: "FastAPI & Web Frameworks",
    description: "Build high-performance REST APIs, write validations, and connect databases asynchronously.",
    details: [
      "FastAPI architecture: starlette, pydantic data schemas, and async routing",
      "Dependency Injection system in FastAPI route handlers",
      "Database access: asynchronous ORMs (SQLAlchemy async, Tortoise ORM)",
      "Autogenerated interactive OpenAPI docs generation"
    ]
  }
];

export const interviewQuestions = [
  {
    question: "What are decorators?",
    answer: "Functions that modify behavior of other functions."
  },
  {
    question: "What is a generator?",
    answer: "A function that yields values lazily."
  }
];

export const pageData = {
  title: "Python",
  badge: "Programming Language",
  description:
    "Learn Python from language fundamentals to OOP, Generators, Decorators, AsyncIO and FastAPI.",
  stats: [
    { value: "7", label: "Learning Modules" },
    { value: "25+", label: "Interview Questions" },
    { value: "20+", label: "Core Concepts" },
    { value: "15+", label: "Practical Projects" }
  ],
  roadmap,
  learnConcepts: [
    "Variables & Types",
    "Functions",
    "OOP",
    "Collections",
    "Decorators",
    "Generators",
    "AsyncIO",
    "Exception Handling",
    "File I/O",
    "FastAPI",
    "Testing",
    "Virtual Environments"
  ],
  topics,
  interviewQuestions,
  resources: [
    "Python Docs",
    "Real Python",
    "FastAPI Docs",
    "PyVideo",
    "Talk Python",
    "Learn Python"
  ],
  ctaTitle: "Become Production Ready with Python",
  ctaDescription:
    "Learn core Python fundamentals, generators, decorators, asynchronous coding, APIs and web frameworks."
};